name: vprofile actions
on: workflow_dispatch
env: 
  AWS_REGION: us-east-2
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks
  PROJECT_KEY: vproapp36


jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
    
      - name: Maven test
        run: mvn test
    
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
      
      #setup java 11 to be default ( see sonarscanner rquirement as of 5.x)

      - name: set java 11
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '11'
      

      # Setup sonar scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar scanner
      - name: SonarQube scan
        run: sonar-scanner
             -Dsonar.host.url=${{ secrets.SONAR_URL }} 
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
             -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
             -Dsonar.projectName=vprofile
             -Dsonar.sources=src/
             -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
             -Dsonar.junit.reportsPaths=target/surefire-reports/ 
             -Dsonar.jacoco.reportsPaths=target/jacoco.exec 
             -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
              

        # check the quality gate status
      - name: SonarQube quality gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}


        
      
    
        
